version: '3.8'

services:
  do-read:
    container_name: do-read
    image: 211125674580.dkr.ecr.eu-central-1.amazonaws.com/do-read:1.0.5
    restart: always
    env_file:
      - .env
    ports:
      - '8000:8080'
    environment:
      SPRING_FLYWAY_ENABLED: "false"