spring:
  datasource:
    url: jdbc:tc:postgresql:latest:///testdb
    username: test
    password: test
    driver-class-name: org.testcontainers.jdbc.ContainerDatabaseDriver

  mail:
    host: localhost
    port: 1025
    username:
    password:

    properties:
      mail:
        smtp:
          ssl:
            trust: "*"
          auth: false
          starttls:
            enable: true
          connectiontimeout: 5000
          timeout: 3000
          writetimeout: 5000

auth:
  secret: ${TEST_SECRET}
  expiration-refresh-token-time: 2592000000 # 24 hours (86.400.000 milliseconds) x 30 days 2.592.000.000 milliseconds
  expiration-access-token-time: 3600000 # 60 minutes or 3600 000 milliseconds
  expiration-confirmation-token-time: 1440 # 1 day or 1440 minutes
  expiration-delete-token-time: 1440 # 1 day or 1440 minutes

app:
  uri: http://localhost
  port: 8080