email:
  sender:
    name: "do-read.pl"
    email: "no-reply@iseebugs.pl"
  templates:
    activation:
      subject: "do-read.pl Weryfikacja emaila"
      template: "authorization-email"
      welcome-text: "${name}, witaj w do-read.pl!"
      text1: "Kliknij poniższy przycisk aby potwierdzić swojego emaila."
      text2: "Fajnie, że z nami jesteś!"
    token-expired:
      subject: "do-read.pl Nowy token aktywacyjny"
      template: "authorization-email"
      welcome-text: "${name}, twój nowy link!"
      text1: "Twój link znajdziesz poniżej - kliknij przycisk aby potwierdzić swojego emaila."
      text2:  "Fajnie, że z nami jesteś!"
    activation-successfully:
      subject: "Account activated successfully!"
      template: "success-email"
      welcome-text:
      text1:
      text2:
    reset-password:
      subject: "do-read.pl Nowe hasło"
      template: "authorization-email"
      welcome-text: "${name}, witaj w do-read!"
      text1: "Kliknij poniższy przycisk aby wygenerować nowe hasło:"
      text2: "Fajnie, że z nami jesteś!"
    delete-account:
      subject: "do-read.pl Usunięcie konta"
      template: "authorization-email"
      welcome-text: "${name}, do zobaczenia!"
      text1: "Proszę potwierdź decyzję o usunięciu konta klikając w poniższy przycisk:"
      text2: "Dobrze, że z nami byłeś!"

