email:
  sender:
    name: "ISeeBugs"
    email: "no-reply@iseebugs.pl"
  templates:
    activation:
      subject: "Activate Your Account"
      template: "authorization-email"
      welcome-text: "Welcome to ISeeBugs, ${name}!"
      text1: "Please activate your account using the link below."
      text2: "We are excited to have you."
    token-expired:
      subject: "Activation Token Expired"
      template: "authorization-email"
      welcome-text: "Maybe this time, ${name}!"
      text1: "Activate your account using the regenerated registration confirmation link."
      text2:  "Remember you have only ${minutes} minutes to activate your account."
    activation-successfully:
      subject: "Account activated successfully!"
      template: "success-email"
      welcome-text:
      text1:
      text2:
    reset-password:
      subject: "Reset Your Password"
      template: "information-email"
      welcome-text: "Welcome to ISeeBugs, ${name}!"
      text1: "This is your new password:"
      text2: "See you soon."
    delete-account:
      subject: "Account deleted"
      template: "authorization-email"
      welcome-text: "Welcome to ISeeBugs, ${name}!"
      text1: "Please click link to successfully delete your account"
      text2: "See you soon."

