email:
  sender:
    name: "ISeeBugs"
    email: "no-reply@iseebugs.pl"
  templates:
    activation:
      subject: "do-read potwierdzenie maila"
      template: "authorization-email"
      welcome-text: "${name}, witaj w do-read!"
      text1: "Proszę potwierdź swojego maila klikając w poniższy link:"
      text2: "Fajnie, że jesteś!"
    token-expired:
      subject: "do-read potwierdzenie maila"
      template: "authorization-email"
      welcome-text: "${name}, twój nowy link!"
      text1: "Potwierdź swojego maila klikając w nowowygenerowany link aktywacyjny:"
      text2:  "Pamiętaj masz tylko ${minutes} minut na skorzystanie z linku. Potem musisz go wygenerować na nowo."
    activation-successfully:
      subject: "Account activated successfully!"
      template: "success-email"
      welcome-text:
      text1:
      text2:
    reset-password:
      subject: "do-read nowe hasło"
      template: "authorization-email"
      welcome-text: "${name}, witaj w do-read!"
      text1: "Oto twoje nowe hasło:"
      text2: "Do zobaczenia wkrótce"
    delete-account:
      subject: "do-read usunięcie konta"
      template: "authorization-email"
      welcome-text: "${name}, do zobaczenia!"
      text1: "Proszę potwierdź decyzję o usunięciu konta klikając w poniższy link:"
      text2: "Dobrze, że z nami byłeś!"

