sentences:
  polish:
    - mama
    - tata
    - brat
    - siostra
    - babcia
    - dziadek
    - buła
    - banan
    - chleb
    - marchewka
    - dynia
    - mus
    - zupa
    - woda
    - mleko
    - kaszka
    - pies
    - kot
    - osioł
    - słoń
    - tygrys
    - wąż
    - mysz
    - lew
    - hipopotam
    - małpa
    - kogut
    - koń
    - owca
    - baran
    - łyżka
    - miska
    - talerz
    - nóż
    - kubek
    - stół
    - krzesło
    - łóżko
    - fotel
    - drzwi
    - lampa
    - kuchnia
    - łazienka
    - pokój
    - jabłko
    - pomarańcz
    - brzoskwinia
    - winogrono
    - brokuł
    - ziemniak
    - pomidor
    - włoszczyzna
    - pomidor
    - ogórek
    - pietruszka
    - bakłażan
    - arbuz
    - samochód
    - samolot
    - rakieta
    - rower
    - hulajnoga
    - statek
    - żaglówka
    - deskorolka
    - łyżwy
    - rakieta
    - prom
    - księżyc
    - chmury
    - słońce
    - gwiazdy
    - planeta
    - satelita
    - kometa
    - wilk
    - niedźwiedź
    - lis
    - borsuk
    - ryś
    - żubr
    - bocian
    - wrona
    - orzeł
    - kawka
    - nietoperz
    - kwiat
    - drzewo
    - las
    - trawa
    - doniczka
    - mrówka
    - osa
    - pszczoła
    - biedronka
    - świerszcz
    - bąk
    - pelikan
    - zegar
    - czas