sentences:
  polish:
    - mama
    - tata
    - brat
    - siostra
    - babcia
    - dziadek
    - buła
    - banan
    - chleb
    - marchewka
    - dynia
    - mus
    - zupa
    - woda
    - mleko
    - kaszka
    - pies
    - kot
    - osioł
    - słoń
    - tygrys
    - wąż
    - mysz
    - lew
    - hipopotam
    - małpa
    - kogut
    - koń
    - owca
    - baran
    - łyżka
    - miska
    - talerz
    - nóż
    - kubek
    - stół
    - krzesło
    - łóżko
    - fotel
    - drzwi
    - lampa
    - kuchnia
    - łazienka
    - pokój
    - jabłko
    - pomarańcz
    - brzoskwinia
    - winogrono
    - brokuł
    - ziemniak
    - pomidor
    - włoszczyzna
    - pomidor
    - ogórek
    - pietruszka
    - bakłażan
    - arbuz
    - samochód
    - samolot
    - rakieta
    - rower
    - hulajnoga
    - statek
    - żaglówka
    - deskorolka
    - łyżwy
    - rakieta
    - prom
    - księżyc
    - chmury
    - słońce
    - gwiazdy
    - planeta
    - satelita
    - kometa
    - wilk
    - niedźwiedź
    - lis
    - borsuk
    - ryś
    - żubr
    - bocian
    - wrona
    - orzeł
    - kawka
    - nietoperz
    - kwiat
    - drzewo
    - trawa
    - doniczka
    - mrówka
    - osa
    - pszczoła
    - biedronka
    - świerszcz
    - bąk
    - pelikan
    - zegar
    - czas
    - ciocia
    - wujek
    - żółty
    - niebieski
    - czerwony
    - zielony
    - szary
    - góra
    - dolina
    - rzeka
    - las
    - polana
    - czarny
    - biały
    - pomarańczowy
    - łąka
    - biegać
    - skakać
    - śpiewać
    - krzyczeć
    - leżeć
    - bujać
    - stoję
    - król
    - pirat
    - zabawa
    - fajny
    - smutny
    - młody
    - stary
    - kapelusz
    - płaszcz
    - zdjęcie
    - okręt
    - bóbr
    - ser
    - szynka
    - śledź
    - pielucha
    - obiad
    - śniadanie
    - kolacja
    - pluszak
    - lego
    - miecz
    - szabla
    - rycerz
    - dzida
    - tarcza
    - księżniczka
    - suknia
    - diadem
    - berło
    - smok
    - straszny
    - ogień
    - gorąco
    - lawa
    - wulkan
    - wyspa
    - plaża
    - piasek
    - statek piracki
    - flaga
    - żeglarz
    - maszt
    - armata
    - szalupa ratunkowa
    - lina
    - kanapka
    - prowiant
    - skrzynia skarbów
    - monety
    - złoto
    - diamenty
    - świecidełka
    - złoty puchar
    - morze
    - fale
    - bryza
    - sztorm
    - błyskawica
    - trząść się
    - strach
    - radość
    - delfin
    - rekin
    - wieloryb
    - ławica ryb
    - mewa
    - krab
    - wydmy
    - kopać
    - ukryć skarb
    - mapa
    - znak
    - zły pirat
    - wielki król
    - jesteś
    - pływać
    - małe krzesło
    - wstążka
    - hak
    - szara myszka
    - sałatka
    - kły
    - ostry miecz
    - pieniądze
    - miła lala
    - pluje
    - żółty kwiat
    - dzik
    - różowa księżniczka
    - zapałka
    - łagodny kot
    - kromka
    - suchy chleb
    - powietrze
    - smaczny kotlet
    - jesień
    - brązowy kasztan
    - przeziębienie
    - gorzkie lekarstwo
    - Pinokio
    - długi nos
    - pajacyk
    - żółta kukurydza
    - Lubię placki
    - magnes
    - to mój pies
    - borówki
    - błękitne niebo
    - stary kościół
    - idę spać
    - lubię skakać
    - kroję chleb
    - głośno krzyczę
    - centymetr
    - z plasteliny
    - patrz na
    - skoczny tygrys
    - kaszanka
    - czarna owca
    - groźny lew
    - jestem super
    - odważny chłopiec
    - gdakanie
    - okrągła piłka
    - smaczna kaszka
    - zielona papryka
    - żółte słońce
    - mama Muminka
    - Reksio
    - Bolek i Lolek
    - miękka owieczka
    - pokazywać palcem
    - pojawiać się
    - zabawa w chowanego
    - cichy mruk
    - księżyc w pełni
    - spokojna piosenka
    - stara krypa
    - szybki samolot
    - jestem bardzo mądry
    - lubię szybko biegać
    - nie lubię szczypania
    - kłujący kaktus
    - gdakająca kura
    - chrupiący chleb
    - mój nocnik
    - pasta do zębów
    - mokra kałuża
    - pięć palców
    - nieprzebyty las
    - złota moneta
    - szmaragdowy kamień
    - dźwięczna muzyka
    - błahy problem
    - lubię wysoko skakać
    - nie będe tam szedł
    - nie widzę problemu
    - zabawa w piaskownicy
    - szlaban się podnosi
    - samochód skręca w prawo
    - odyseja kosmiczna
    - ekstremalne przyspieszenia
    - szorstki papier
    - miękki kot mruczy
    - pies gryzie kość
    - Marcin szybko biega
    - ładowarka do telefonu
    - drzwi szeroko otwarte
    - drewniana więźba dachowa
    - żółty jesienny liść
    - te żelki są kwaśne
    - autostopem przez galaktykę
    - przygody kota Filemona
    - Bonifacy leży na zapiecku
    - lubię smakowite kąski